version: '2.2'
services:
  jenkins:
    container_name: jenkins
    image: timwebster9/jenkins-cac
    build: .
    ports:
      - '8088:8080'
    environment:
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/jenkins.yaml
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    volumes:
      - './jenkins.yaml:/usr/share/jenkins/jenkins.yaml'