version: '2.2'
services:
  jenkins:
    container_name: jenkins
    image: timwebster9/jenkins-cac
    build: .
    ports:
      - '8088:8080'
    environment:
      - CASC_JENKINS_CONFIG=https://raw.githubusercontent.com/timwebster9/jenkins-cac/master/jenkins.yaml
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"